apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/basanta4043/regmibasanta-gitops.git
    path: apps/frontend
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-env
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
